// Mocks generated by Mockito 5.4.4 from annotations
// in blytz_flutter_app/test/integration/backend_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blytz_flutter_app/core/errors/failures.dart' as _i7;
import 'package:blytz_flutter_app/core/network/api_client.dart' as _i2;
import 'package:blytz_flutter_app/features/auth/data/models/auth_model.dart'
    as _i3;
import 'package:blytz_flutter_app/features/auth/data/repositories/auth_repository_impl.dart'
    as _i5;
import 'package:either_dart/either.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthApiClient_0 extends _i1.SmartFake implements _i2.AuthApiClient {
  _FakeAuthApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductApiClient_1 extends _i1.SmartFake
    implements _i2.ProductApiClient {
  _FakeProductApiClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuctionApiClient_2 extends _i1.SmartFake
    implements _i2.AuctionApiClient {
  _FakeAuctionApiClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderApiClient_3 extends _i1.SmartFake
    implements _i2.OrderApiClient {
  _FakeOrderApiClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentApiClient_4 extends _i1.SmartFake
    implements _i2.PaymentApiClient {
  _FakePaymentApiClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_5 extends _i1.SmartFake implements _i3.AuthResponse {
  _FakeAuthResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthModel_6 extends _i1.SmartFake implements _i3.AuthModel {
  _FakeAuthModel_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthApiClient get authClient => (super.noSuchMethod(
        Invocation.getter(#authClient),
        returnValue: _FakeAuthApiClient_0(
          this,
          Invocation.getter(#authClient),
        ),
      ) as _i2.AuthApiClient);

  @override
  _i2.ProductApiClient get productClient => (super.noSuchMethod(
        Invocation.getter(#productClient),
        returnValue: _FakeProductApiClient_1(
          this,
          Invocation.getter(#productClient),
        ),
      ) as _i2.ProductApiClient);

  @override
  _i2.AuctionApiClient get auctionClient => (super.noSuchMethod(
        Invocation.getter(#auctionClient),
        returnValue: _FakeAuctionApiClient_2(
          this,
          Invocation.getter(#auctionClient),
        ),
      ) as _i2.AuctionApiClient);

  @override
  _i2.OrderApiClient get orderClient => (super.noSuchMethod(
        Invocation.getter(#orderClient),
        returnValue: _FakeOrderApiClient_3(
          this,
          Invocation.getter(#orderClient),
        ),
      ) as _i2.OrderApiClient);

  @override
  _i2.PaymentApiClient get paymentClient => (super.noSuchMethod(
        Invocation.getter(#paymentClient),
        returnValue: _FakePaymentApiClient_4(
          this,
          Invocation.getter(#paymentClient),
        ),
      ) as _i2.PaymentApiClient);

  @override
  _i4.Future<_i3.AuthResponse> login(_i3.LoginRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i4.Future<_i3.AuthResponse>.value(_FakeAuthResponse_5(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.AuthResponse> register(_i3.RegisterRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [request],
        ),
        returnValue: _i4.Future<_i3.AuthResponse>.value(_FakeAuthResponse_5(
          this,
          Invocation.method(
            #register,
            [request],
          ),
        )),
      ) as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.AuthResponse> refreshToken(_i3.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [request],
        ),
        returnValue: _i4.Future<_i3.AuthResponse>.value(_FakeAuthResponse_5(
          this,
          Invocation.method(
            #refreshToken,
            [request],
          ),
        )),
      ) as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<void> logout(String? token) => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.AuthModel> getCurrentUser(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [token],
        ),
        returnValue: _i4.Future<_i3.AuthModel>.value(_FakeAuthModel_6(
          this,
          Invocation.method(
            #getCurrentUser,
            [token],
          ),
        )),
      ) as _i4.Future<_i3.AuthModel>);

  @override
  _i4.Future<_i3.AuthModel> updateProfile(
    String? token,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [
            token,
            request,
          ],
        ),
        returnValue: _i4.Future<_i3.AuthModel>.value(_FakeAuthModel_6(
          this,
          Invocation.method(
            #updateProfile,
            [
              token,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i3.AuthModel>);

  @override
  _i4.Future<Map<String, dynamic>> getProducts({
    int? page = 1,
    int? limit = 20,
    String? category,
    String? search,
    double? minPrice,
    double? maxPrice,
    bool? featured,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
          {
            #page: page,
            #limit: limit,
            #category: category,
            #search: search,
            #minPrice: minPrice,
            #maxPrice: maxPrice,
            #featured: featured,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getProduct(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [id],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createProduct(
    String? token,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [
            token,
            request,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getFeaturedProducts({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeaturedProducts,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getAuctions({
    int? page = 1,
    int? limit = 20,
    String? category,
    String? status,
    String? sellerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuctions,
          [],
          {
            #page: page,
            #limit: limit,
            #category: category,
            #status: status,
            #sellerId: sellerId,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getActiveAuctions({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveAuctions,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getAuction(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuction,
          [id],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getAuctionBids(
    String? id, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuctionBids,
          [id],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createAuction(
    String? token,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAuction,
          [
            token,
            request,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateAuction(
    String? token,
    String? id,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAuction,
          [
            token,
            id,
            request,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> deleteAuction(
    String? token,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAuction,
          [
            token,
            id,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> placeBid(
    String? token,
    String? auctionId,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #placeBid,
          [
            token,
            auctionId,
            request,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createOrder(
    String? token,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [
            token,
            request,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getOrder(
    String? token,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [
            token,
            id,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getMyOrders(
    String? token, {
    int? page = 1,
    int? limit = 20,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyOrders,
          [token],
          {
            #page: page,
            #limit: limit,
            #status: status,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> processPayment(
    String? token,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processPayment,
          [
            token,
            request,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getPaymentStatus(
    String? token,
    String? paymentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentStatus,
          [
            token,
            paymentId,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> verifyToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyToken,
          [token],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i3.AuthResponse>> login(
          _i3.LoginRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue:
            _i4.Future<_i6.Either<_i7.Failure, _i3.AuthResponse>>.value(
                _i8.dummyValue<_i6.Either<_i7.Failure, _i3.AuthResponse>>(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i4.Future<_i6.Either<_i7.Failure, _i3.AuthResponse>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i3.AuthResponse>> register(
          _i3.RegisterRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [request],
        ),
        returnValue:
            _i4.Future<_i6.Either<_i7.Failure, _i3.AuthResponse>>.value(
                _i8.dummyValue<_i6.Either<_i7.Failure, _i3.AuthResponse>>(
          this,
          Invocation.method(
            #register,
            [request],
          ),
        )),
      ) as _i4.Future<_i6.Either<_i7.Failure, _i3.AuthResponse>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i3.AuthResponse>> refreshToken(
          _i3.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [request],
        ),
        returnValue:
            _i4.Future<_i6.Either<_i7.Failure, _i3.AuthResponse>>.value(
                _i8.dummyValue<_i6.Either<_i7.Failure, _i3.AuthResponse>>(
          this,
          Invocation.method(
            #refreshToken,
            [request],
          ),
        )),
      ) as _i4.Future<_i6.Either<_i7.Failure, _i3.AuthResponse>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i6.Either<_i7.Failure, void>>.value(
            _i8.dummyValue<_i6.Either<_i7.Failure, void>>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i3.AuthModel>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i6.Either<_i7.Failure, _i3.AuthModel>>.value(
            _i8.dummyValue<_i6.Either<_i7.Failure, _i3.AuthModel>>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i6.Either<_i7.Failure, _i3.AuthModel>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i3.AuthModel>> updateProfile(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [request],
        ),
        returnValue: _i4.Future<_i6.Either<_i7.Failure, _i3.AuthModel>>.value(
            _i8.dummyValue<_i6.Either<_i7.Failure, _i3.AuthModel>>(
          this,
          Invocation.method(
            #updateProfile,
            [request],
          ),
        )),
      ) as _i4.Future<_i6.Either<_i7.Failure, _i3.AuthModel>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, bool>> isTokenValid() =>
      (super.noSuchMethod(
        Invocation.method(
          #isTokenValid,
          [],
        ),
        returnValue: _i4.Future<_i6.Either<_i7.Failure, bool>>.value(
            _i8.dummyValue<_i6.Either<_i7.Failure, bool>>(
          this,
          Invocation.method(
            #isTokenValid,
            [],
          ),
        )),
      ) as _i4.Future<_i6.Either<_i7.Failure, bool>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, String?>> getStoredToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #getStoredToken,
          [],
        ),
        returnValue: _i4.Future<_i6.Either<_i7.Failure, String?>>.value(
            _i8.dummyValue<_i6.Either<_i7.Failure, String?>>(
          this,
          Invocation.method(
            #getStoredToken,
            [],
          ),
        )),
      ) as _i4.Future<_i6.Either<_i7.Failure, String?>>);
}
